name: build
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Windows:
    runs-on: windows-2019
    env:
      VS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\'
      MSBUILD_PATH: >-
        C:\Program Files (x86)\Microsoft Visual
        Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also emits such aliases as lts, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
          node-version: '18.x'
      - uses: actions/checkout@v1
        with:
          fetch-dept: 1
      - name: install boost
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
          cd boost
          /\bootstrap.bat
      - name: Boost headers
        run: |
          cd boost
          .\b2 headers
      - name: Build libtorrent
        shell: cmd
        run: |
          set BOOST_ROOT=%CD%\boost
          set PATH=%BOOST_ROOT%;%PATH%
          npm i && npm run build:windows
      - name: create zip archive
        shell: pwsh
        run: |
          Compress-Archive -Path ".\build\Release" -DestinationPath ".\libtorrent_windows.zip"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./libtorrent_windows.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use in SemVer notation.
          # It also emits such aliases as lts, latest, nightly and canary builds
          # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node 
          node-version: '18.x'
      - uses: actions/checkout@v1
        with:
          fetch-dept: 1
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -y libboost-all-dev
      - name: Build libtorrent
        run: |
          npm i && npm run build
      - name: create zip archive
        run: |
          zip -r release-linux-amd64.zip "$(pwd)/build/Release"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "./release-linux-amd64.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # MacOS:
  #   runs-on: macOS-latest
  #   steps:
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: '18.x'
  #   - uses: actions/checkout@v1
  #   - name: Install Dependencies
  #     run: |
  #       brew update && brew install boost
  #   - name: Build Project
  #     run: |
  #       npm i && npm run build
